// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"pie/internal/data/model"
)

func newChunkInfo(db *gorm.DB, opts ...gen.DOOption) chunkInfo {
	_chunkInfo := chunkInfo{}

	_chunkInfo.chunkInfoDo.UseDB(db, opts...)
	_chunkInfo.chunkInfoDo.UseModel(&model.ChunkInfo{})

	tableName := _chunkInfo.chunkInfoDo.TableName()
	_chunkInfo.ALL = field.NewAsterisk(tableName)
	_chunkInfo.ID = field.NewInt64(tableName, "id")
	_chunkInfo.FileMd5 = field.NewString(tableName, "file_md5")
	_chunkInfo.ChunkIndex = field.NewInt32(tableName, "chunk_index")
	_chunkInfo.ChunkMd5 = field.NewString(tableName, "chunk_md5")
	_chunkInfo.StoragePath = field.NewString(tableName, "storage_path")

	_chunkInfo.fillFieldMap()

	return _chunkInfo
}

type chunkInfo struct {
	chunkInfoDo chunkInfoDo

	ALL         field.Asterisk
	ID          field.Int64
	FileMd5     field.String // MD5
	ChunkIndex  field.Int32
	ChunkMd5    field.String // MD5
	StoragePath field.String

	fieldMap map[string]field.Expr
}

func (c chunkInfo) Table(newTableName string) *chunkInfo {
	c.chunkInfoDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c chunkInfo) As(alias string) *chunkInfo {
	c.chunkInfoDo.DO = *(c.chunkInfoDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *chunkInfo) updateTableName(table string) *chunkInfo {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewInt64(table, "id")
	c.FileMd5 = field.NewString(table, "file_md5")
	c.ChunkIndex = field.NewInt32(table, "chunk_index")
	c.ChunkMd5 = field.NewString(table, "chunk_md5")
	c.StoragePath = field.NewString(table, "storage_path")

	c.fillFieldMap()

	return c
}

func (c *chunkInfo) WithContext(ctx context.Context) IChunkInfoDo {
	return c.chunkInfoDo.WithContext(ctx)
}

func (c chunkInfo) TableName() string { return c.chunkInfoDo.TableName() }

func (c chunkInfo) Alias() string { return c.chunkInfoDo.Alias() }

func (c chunkInfo) Columns(cols ...field.Expr) gen.Columns { return c.chunkInfoDo.Columns(cols...) }

func (c *chunkInfo) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *chunkInfo) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 5)
	c.fieldMap["id"] = c.ID
	c.fieldMap["file_md5"] = c.FileMd5
	c.fieldMap["chunk_index"] = c.ChunkIndex
	c.fieldMap["chunk_md5"] = c.ChunkMd5
	c.fieldMap["storage_path"] = c.StoragePath
}

func (c chunkInfo) clone(db *gorm.DB) chunkInfo {
	c.chunkInfoDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c chunkInfo) replaceDB(db *gorm.DB) chunkInfo {
	c.chunkInfoDo.ReplaceDB(db)
	return c
}

type chunkInfoDo struct{ gen.DO }

type IChunkInfoDo interface {
	gen.SubQuery
	Debug() IChunkInfoDo
	WithContext(ctx context.Context) IChunkInfoDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IChunkInfoDo
	WriteDB() IChunkInfoDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IChunkInfoDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IChunkInfoDo
	Not(conds ...gen.Condition) IChunkInfoDo
	Or(conds ...gen.Condition) IChunkInfoDo
	Select(conds ...field.Expr) IChunkInfoDo
	Where(conds ...gen.Condition) IChunkInfoDo
	Order(conds ...field.Expr) IChunkInfoDo
	Distinct(cols ...field.Expr) IChunkInfoDo
	Omit(cols ...field.Expr) IChunkInfoDo
	Join(table schema.Tabler, on ...field.Expr) IChunkInfoDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IChunkInfoDo
	RightJoin(table schema.Tabler, on ...field.Expr) IChunkInfoDo
	Group(cols ...field.Expr) IChunkInfoDo
	Having(conds ...gen.Condition) IChunkInfoDo
	Limit(limit int) IChunkInfoDo
	Offset(offset int) IChunkInfoDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IChunkInfoDo
	Unscoped() IChunkInfoDo
	Create(values ...*model.ChunkInfo) error
	CreateInBatches(values []*model.ChunkInfo, batchSize int) error
	Save(values ...*model.ChunkInfo) error
	First() (*model.ChunkInfo, error)
	Take() (*model.ChunkInfo, error)
	Last() (*model.ChunkInfo, error)
	Find() ([]*model.ChunkInfo, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ChunkInfo, err error)
	FindInBatches(result *[]*model.ChunkInfo, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.ChunkInfo) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IChunkInfoDo
	Assign(attrs ...field.AssignExpr) IChunkInfoDo
	Joins(fields ...field.RelationField) IChunkInfoDo
	Preload(fields ...field.RelationField) IChunkInfoDo
	FirstOrInit() (*model.ChunkInfo, error)
	FirstOrCreate() (*model.ChunkInfo, error)
	FindByPage(offset int, limit int) (result []*model.ChunkInfo, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IChunkInfoDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c chunkInfoDo) Debug() IChunkInfoDo {
	return c.withDO(c.DO.Debug())
}

func (c chunkInfoDo) WithContext(ctx context.Context) IChunkInfoDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c chunkInfoDo) ReadDB() IChunkInfoDo {
	return c.Clauses(dbresolver.Read)
}

func (c chunkInfoDo) WriteDB() IChunkInfoDo {
	return c.Clauses(dbresolver.Write)
}

func (c chunkInfoDo) Session(config *gorm.Session) IChunkInfoDo {
	return c.withDO(c.DO.Session(config))
}

func (c chunkInfoDo) Clauses(conds ...clause.Expression) IChunkInfoDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c chunkInfoDo) Returning(value interface{}, columns ...string) IChunkInfoDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c chunkInfoDo) Not(conds ...gen.Condition) IChunkInfoDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c chunkInfoDo) Or(conds ...gen.Condition) IChunkInfoDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c chunkInfoDo) Select(conds ...field.Expr) IChunkInfoDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c chunkInfoDo) Where(conds ...gen.Condition) IChunkInfoDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c chunkInfoDo) Order(conds ...field.Expr) IChunkInfoDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c chunkInfoDo) Distinct(cols ...field.Expr) IChunkInfoDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c chunkInfoDo) Omit(cols ...field.Expr) IChunkInfoDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c chunkInfoDo) Join(table schema.Tabler, on ...field.Expr) IChunkInfoDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c chunkInfoDo) LeftJoin(table schema.Tabler, on ...field.Expr) IChunkInfoDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c chunkInfoDo) RightJoin(table schema.Tabler, on ...field.Expr) IChunkInfoDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c chunkInfoDo) Group(cols ...field.Expr) IChunkInfoDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c chunkInfoDo) Having(conds ...gen.Condition) IChunkInfoDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c chunkInfoDo) Limit(limit int) IChunkInfoDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c chunkInfoDo) Offset(offset int) IChunkInfoDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c chunkInfoDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IChunkInfoDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c chunkInfoDo) Unscoped() IChunkInfoDo {
	return c.withDO(c.DO.Unscoped())
}

func (c chunkInfoDo) Create(values ...*model.ChunkInfo) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c chunkInfoDo) CreateInBatches(values []*model.ChunkInfo, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c chunkInfoDo) Save(values ...*model.ChunkInfo) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c chunkInfoDo) First() (*model.ChunkInfo, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ChunkInfo), nil
	}
}

func (c chunkInfoDo) Take() (*model.ChunkInfo, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ChunkInfo), nil
	}
}

func (c chunkInfoDo) Last() (*model.ChunkInfo, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ChunkInfo), nil
	}
}

func (c chunkInfoDo) Find() ([]*model.ChunkInfo, error) {
	result, err := c.DO.Find()
	return result.([]*model.ChunkInfo), err
}

func (c chunkInfoDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ChunkInfo, err error) {
	buf := make([]*model.ChunkInfo, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c chunkInfoDo) FindInBatches(result *[]*model.ChunkInfo, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c chunkInfoDo) Attrs(attrs ...field.AssignExpr) IChunkInfoDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c chunkInfoDo) Assign(attrs ...field.AssignExpr) IChunkInfoDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c chunkInfoDo) Joins(fields ...field.RelationField) IChunkInfoDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c chunkInfoDo) Preload(fields ...field.RelationField) IChunkInfoDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c chunkInfoDo) FirstOrInit() (*model.ChunkInfo, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ChunkInfo), nil
	}
}

func (c chunkInfoDo) FirstOrCreate() (*model.ChunkInfo, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ChunkInfo), nil
	}
}

func (c chunkInfoDo) FindByPage(offset int, limit int) (result []*model.ChunkInfo, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c chunkInfoDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c chunkInfoDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c chunkInfoDo) Delete(models ...*model.ChunkInfo) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *chunkInfoDo) withDO(do gen.Dao) *chunkInfoDo {
	c.DO = *do.(*gen.DO)
	return c
}
