// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"pie/internal/data/model"
)

func newDocumentVector(db *gorm.DB, opts ...gen.DOOption) documentVector {
	_documentVector := documentVector{}

	_documentVector.documentVectorDo.UseDB(db, opts...)
	_documentVector.documentVectorDo.UseModel(&model.DocumentVector{})

	tableName := _documentVector.documentVectorDo.TableName()
	_documentVector.ALL = field.NewAsterisk(tableName)
	_documentVector.VectorID = field.NewInt64(tableName, "vector_id")
	_documentVector.FileMd5 = field.NewString(tableName, "file_md5")
	_documentVector.ChunkID = field.NewInt32(tableName, "chunk_id")
	_documentVector.TextContent = field.NewString(tableName, "text_content")
	_documentVector.ModelVersion = field.NewString(tableName, "model_version")
	_documentVector.UserID = field.NewString(tableName, "user_id")
	_documentVector.OrgTag = field.NewString(tableName, "org_tag")
	_documentVector.IsPublic = field.NewBool(tableName, "is_public")

	_documentVector.fillFieldMap()

	return _documentVector
}

type documentVector struct {
	documentVectorDo documentVectorDo

	ALL          field.Asterisk
	VectorID     field.Int64
	FileMd5      field.String // MD5
	ChunkID      field.Int32
	TextContent  field.String
	ModelVersion field.String
	UserID       field.String // ID
	OrgTag       field.String
	IsPublic     field.Bool

	fieldMap map[string]field.Expr
}

func (d documentVector) Table(newTableName string) *documentVector {
	d.documentVectorDo.UseTable(newTableName)
	return d.updateTableName(newTableName)
}

func (d documentVector) As(alias string) *documentVector {
	d.documentVectorDo.DO = *(d.documentVectorDo.As(alias).(*gen.DO))
	return d.updateTableName(alias)
}

func (d *documentVector) updateTableName(table string) *documentVector {
	d.ALL = field.NewAsterisk(table)
	d.VectorID = field.NewInt64(table, "vector_id")
	d.FileMd5 = field.NewString(table, "file_md5")
	d.ChunkID = field.NewInt32(table, "chunk_id")
	d.TextContent = field.NewString(table, "text_content")
	d.ModelVersion = field.NewString(table, "model_version")
	d.UserID = field.NewString(table, "user_id")
	d.OrgTag = field.NewString(table, "org_tag")
	d.IsPublic = field.NewBool(table, "is_public")

	d.fillFieldMap()

	return d
}

func (d *documentVector) WithContext(ctx context.Context) IDocumentVectorDo {
	return d.documentVectorDo.WithContext(ctx)
}

func (d documentVector) TableName() string { return d.documentVectorDo.TableName() }

func (d documentVector) Alias() string { return d.documentVectorDo.Alias() }

func (d documentVector) Columns(cols ...field.Expr) gen.Columns {
	return d.documentVectorDo.Columns(cols...)
}

func (d *documentVector) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := d.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (d *documentVector) fillFieldMap() {
	d.fieldMap = make(map[string]field.Expr, 8)
	d.fieldMap["vector_id"] = d.VectorID
	d.fieldMap["file_md5"] = d.FileMd5
	d.fieldMap["chunk_id"] = d.ChunkID
	d.fieldMap["text_content"] = d.TextContent
	d.fieldMap["model_version"] = d.ModelVersion
	d.fieldMap["user_id"] = d.UserID
	d.fieldMap["org_tag"] = d.OrgTag
	d.fieldMap["is_public"] = d.IsPublic
}

func (d documentVector) clone(db *gorm.DB) documentVector {
	d.documentVectorDo.ReplaceConnPool(db.Statement.ConnPool)
	return d
}

func (d documentVector) replaceDB(db *gorm.DB) documentVector {
	d.documentVectorDo.ReplaceDB(db)
	return d
}

type documentVectorDo struct{ gen.DO }

type IDocumentVectorDo interface {
	gen.SubQuery
	Debug() IDocumentVectorDo
	WithContext(ctx context.Context) IDocumentVectorDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IDocumentVectorDo
	WriteDB() IDocumentVectorDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IDocumentVectorDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IDocumentVectorDo
	Not(conds ...gen.Condition) IDocumentVectorDo
	Or(conds ...gen.Condition) IDocumentVectorDo
	Select(conds ...field.Expr) IDocumentVectorDo
	Where(conds ...gen.Condition) IDocumentVectorDo
	Order(conds ...field.Expr) IDocumentVectorDo
	Distinct(cols ...field.Expr) IDocumentVectorDo
	Omit(cols ...field.Expr) IDocumentVectorDo
	Join(table schema.Tabler, on ...field.Expr) IDocumentVectorDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IDocumentVectorDo
	RightJoin(table schema.Tabler, on ...field.Expr) IDocumentVectorDo
	Group(cols ...field.Expr) IDocumentVectorDo
	Having(conds ...gen.Condition) IDocumentVectorDo
	Limit(limit int) IDocumentVectorDo
	Offset(offset int) IDocumentVectorDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IDocumentVectorDo
	Unscoped() IDocumentVectorDo
	Create(values ...*model.DocumentVector) error
	CreateInBatches(values []*model.DocumentVector, batchSize int) error
	Save(values ...*model.DocumentVector) error
	First() (*model.DocumentVector, error)
	Take() (*model.DocumentVector, error)
	Last() (*model.DocumentVector, error)
	Find() ([]*model.DocumentVector, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DocumentVector, err error)
	FindInBatches(result *[]*model.DocumentVector, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.DocumentVector) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IDocumentVectorDo
	Assign(attrs ...field.AssignExpr) IDocumentVectorDo
	Joins(fields ...field.RelationField) IDocumentVectorDo
	Preload(fields ...field.RelationField) IDocumentVectorDo
	FirstOrInit() (*model.DocumentVector, error)
	FirstOrCreate() (*model.DocumentVector, error)
	FindByPage(offset int, limit int) (result []*model.DocumentVector, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IDocumentVectorDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (d documentVectorDo) Debug() IDocumentVectorDo {
	return d.withDO(d.DO.Debug())
}

func (d documentVectorDo) WithContext(ctx context.Context) IDocumentVectorDo {
	return d.withDO(d.DO.WithContext(ctx))
}

func (d documentVectorDo) ReadDB() IDocumentVectorDo {
	return d.Clauses(dbresolver.Read)
}

func (d documentVectorDo) WriteDB() IDocumentVectorDo {
	return d.Clauses(dbresolver.Write)
}

func (d documentVectorDo) Session(config *gorm.Session) IDocumentVectorDo {
	return d.withDO(d.DO.Session(config))
}

func (d documentVectorDo) Clauses(conds ...clause.Expression) IDocumentVectorDo {
	return d.withDO(d.DO.Clauses(conds...))
}

func (d documentVectorDo) Returning(value interface{}, columns ...string) IDocumentVectorDo {
	return d.withDO(d.DO.Returning(value, columns...))
}

func (d documentVectorDo) Not(conds ...gen.Condition) IDocumentVectorDo {
	return d.withDO(d.DO.Not(conds...))
}

func (d documentVectorDo) Or(conds ...gen.Condition) IDocumentVectorDo {
	return d.withDO(d.DO.Or(conds...))
}

func (d documentVectorDo) Select(conds ...field.Expr) IDocumentVectorDo {
	return d.withDO(d.DO.Select(conds...))
}

func (d documentVectorDo) Where(conds ...gen.Condition) IDocumentVectorDo {
	return d.withDO(d.DO.Where(conds...))
}

func (d documentVectorDo) Order(conds ...field.Expr) IDocumentVectorDo {
	return d.withDO(d.DO.Order(conds...))
}

func (d documentVectorDo) Distinct(cols ...field.Expr) IDocumentVectorDo {
	return d.withDO(d.DO.Distinct(cols...))
}

func (d documentVectorDo) Omit(cols ...field.Expr) IDocumentVectorDo {
	return d.withDO(d.DO.Omit(cols...))
}

func (d documentVectorDo) Join(table schema.Tabler, on ...field.Expr) IDocumentVectorDo {
	return d.withDO(d.DO.Join(table, on...))
}

func (d documentVectorDo) LeftJoin(table schema.Tabler, on ...field.Expr) IDocumentVectorDo {
	return d.withDO(d.DO.LeftJoin(table, on...))
}

func (d documentVectorDo) RightJoin(table schema.Tabler, on ...field.Expr) IDocumentVectorDo {
	return d.withDO(d.DO.RightJoin(table, on...))
}

func (d documentVectorDo) Group(cols ...field.Expr) IDocumentVectorDo {
	return d.withDO(d.DO.Group(cols...))
}

func (d documentVectorDo) Having(conds ...gen.Condition) IDocumentVectorDo {
	return d.withDO(d.DO.Having(conds...))
}

func (d documentVectorDo) Limit(limit int) IDocumentVectorDo {
	return d.withDO(d.DO.Limit(limit))
}

func (d documentVectorDo) Offset(offset int) IDocumentVectorDo {
	return d.withDO(d.DO.Offset(offset))
}

func (d documentVectorDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IDocumentVectorDo {
	return d.withDO(d.DO.Scopes(funcs...))
}

func (d documentVectorDo) Unscoped() IDocumentVectorDo {
	return d.withDO(d.DO.Unscoped())
}

func (d documentVectorDo) Create(values ...*model.DocumentVector) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Create(values)
}

func (d documentVectorDo) CreateInBatches(values []*model.DocumentVector, batchSize int) error {
	return d.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (d documentVectorDo) Save(values ...*model.DocumentVector) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Save(values)
}

func (d documentVectorDo) First() (*model.DocumentVector, error) {
	if result, err := d.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.DocumentVector), nil
	}
}

func (d documentVectorDo) Take() (*model.DocumentVector, error) {
	if result, err := d.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.DocumentVector), nil
	}
}

func (d documentVectorDo) Last() (*model.DocumentVector, error) {
	if result, err := d.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.DocumentVector), nil
	}
}

func (d documentVectorDo) Find() ([]*model.DocumentVector, error) {
	result, err := d.DO.Find()
	return result.([]*model.DocumentVector), err
}

func (d documentVectorDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DocumentVector, err error) {
	buf := make([]*model.DocumentVector, 0, batchSize)
	err = d.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (d documentVectorDo) FindInBatches(result *[]*model.DocumentVector, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return d.DO.FindInBatches(result, batchSize, fc)
}

func (d documentVectorDo) Attrs(attrs ...field.AssignExpr) IDocumentVectorDo {
	return d.withDO(d.DO.Attrs(attrs...))
}

func (d documentVectorDo) Assign(attrs ...field.AssignExpr) IDocumentVectorDo {
	return d.withDO(d.DO.Assign(attrs...))
}

func (d documentVectorDo) Joins(fields ...field.RelationField) IDocumentVectorDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Joins(_f))
	}
	return &d
}

func (d documentVectorDo) Preload(fields ...field.RelationField) IDocumentVectorDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Preload(_f))
	}
	return &d
}

func (d documentVectorDo) FirstOrInit() (*model.DocumentVector, error) {
	if result, err := d.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.DocumentVector), nil
	}
}

func (d documentVectorDo) FirstOrCreate() (*model.DocumentVector, error) {
	if result, err := d.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.DocumentVector), nil
	}
}

func (d documentVectorDo) FindByPage(offset int, limit int) (result []*model.DocumentVector, count int64, err error) {
	result, err = d.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = d.Offset(-1).Limit(-1).Count()
	return
}

func (d documentVectorDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = d.Count()
	if err != nil {
		return
	}

	err = d.Offset(offset).Limit(limit).Scan(result)
	return
}

func (d documentVectorDo) Scan(result interface{}) (err error) {
	return d.DO.Scan(result)
}

func (d documentVectorDo) Delete(models ...*model.DocumentVector) (result gen.ResultInfo, err error) {
	return d.DO.Delete(models)
}

func (d *documentVectorDo) withDO(do gen.Dao) *documentVectorDo {
	d.DO = *do.(*gen.DO)
	return d
}
