// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q               = new(Query)
	ChunkInfo       *chunkInfo
	DocumentVector  *documentVector
	FileUpload      *fileUpload
	OrganizationTag *organizationTag
	User            *user
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	ChunkInfo = &Q.ChunkInfo
	DocumentVector = &Q.DocumentVector
	FileUpload = &Q.FileUpload
	OrganizationTag = &Q.OrganizationTag
	User = &Q.User
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:              db,
		ChunkInfo:       newChunkInfo(db, opts...),
		DocumentVector:  newDocumentVector(db, opts...),
		FileUpload:      newFileUpload(db, opts...),
		OrganizationTag: newOrganizationTag(db, opts...),
		User:            newUser(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	ChunkInfo       chunkInfo
	DocumentVector  documentVector
	FileUpload      fileUpload
	OrganizationTag organizationTag
	User            user
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) UnderlyingDB() *gorm.DB { return q.db }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:              db,
		ChunkInfo:       q.ChunkInfo.clone(db),
		DocumentVector:  q.DocumentVector.clone(db),
		FileUpload:      q.FileUpload.clone(db),
		OrganizationTag: q.OrganizationTag.clone(db),
		User:            q.User.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:              db,
		ChunkInfo:       q.ChunkInfo.replaceDB(db),
		DocumentVector:  q.DocumentVector.replaceDB(db),
		FileUpload:      q.FileUpload.replaceDB(db),
		OrganizationTag: q.OrganizationTag.replaceDB(db),
		User:            q.User.replaceDB(db),
	}
}

type queryCtx struct {
	ChunkInfo       IChunkInfoDo
	DocumentVector  IDocumentVectorDo
	FileUpload      IFileUploadDo
	OrganizationTag IOrganizationTagDo
	User            IUserDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		ChunkInfo:       q.ChunkInfo.WithContext(ctx),
		DocumentVector:  q.DocumentVector.WithContext(ctx),
		FileUpload:      q.FileUpload.WithContext(ctx),
		OrganizationTag: q.OrganizationTag.WithContext(ctx),
		User:            q.User.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
