// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"pie/internal/data/model"
)

func newOrganizationTag(db *gorm.DB, opts ...gen.DOOption) organizationTag {
	_organizationTag := organizationTag{}

	_organizationTag.organizationTagDo.UseDB(db, opts...)
	_organizationTag.organizationTagDo.UseModel(&model.OrganizationTag{})

	tableName := _organizationTag.organizationTagDo.TableName()
	_organizationTag.ALL = field.NewAsterisk(tableName)
	_organizationTag.TagID = field.NewString(tableName, "tag_id")
	_organizationTag.Name = field.NewString(tableName, "name")
	_organizationTag.Description = field.NewString(tableName, "description")
	_organizationTag.ParentTag = field.NewString(tableName, "parent_tag")
	_organizationTag.CreatedBy = field.NewInt64(tableName, "created_by")
	_organizationTag.CreatedAt = field.NewTime(tableName, "created_at")
	_organizationTag.UpdatedAt = field.NewTime(tableName, "updated_at")

	_organizationTag.fillFieldMap()

	return _organizationTag
}

type organizationTag struct {
	organizationTagDo organizationTagDo

	ALL         field.Asterisk
	TagID       field.String
	Name        field.String
	Description field.String
	ParentTag   field.String // ID
	CreatedBy   field.Int64  // ID
	CreatedAt   field.Time
	UpdatedAt   field.Time

	fieldMap map[string]field.Expr
}

func (o organizationTag) Table(newTableName string) *organizationTag {
	o.organizationTagDo.UseTable(newTableName)
	return o.updateTableName(newTableName)
}

func (o organizationTag) As(alias string) *organizationTag {
	o.organizationTagDo.DO = *(o.organizationTagDo.As(alias).(*gen.DO))
	return o.updateTableName(alias)
}

func (o *organizationTag) updateTableName(table string) *organizationTag {
	o.ALL = field.NewAsterisk(table)
	o.TagID = field.NewString(table, "tag_id")
	o.Name = field.NewString(table, "name")
	o.Description = field.NewString(table, "description")
	o.ParentTag = field.NewString(table, "parent_tag")
	o.CreatedBy = field.NewInt64(table, "created_by")
	o.CreatedAt = field.NewTime(table, "created_at")
	o.UpdatedAt = field.NewTime(table, "updated_at")

	o.fillFieldMap()

	return o
}

func (o *organizationTag) WithContext(ctx context.Context) IOrganizationTagDo {
	return o.organizationTagDo.WithContext(ctx)
}

func (o organizationTag) TableName() string { return o.organizationTagDo.TableName() }

func (o organizationTag) Alias() string { return o.organizationTagDo.Alias() }

func (o organizationTag) Columns(cols ...field.Expr) gen.Columns {
	return o.organizationTagDo.Columns(cols...)
}

func (o *organizationTag) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := o.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (o *organizationTag) fillFieldMap() {
	o.fieldMap = make(map[string]field.Expr, 7)
	o.fieldMap["tag_id"] = o.TagID
	o.fieldMap["name"] = o.Name
	o.fieldMap["description"] = o.Description
	o.fieldMap["parent_tag"] = o.ParentTag
	o.fieldMap["created_by"] = o.CreatedBy
	o.fieldMap["created_at"] = o.CreatedAt
	o.fieldMap["updated_at"] = o.UpdatedAt
}

func (o organizationTag) clone(db *gorm.DB) organizationTag {
	o.organizationTagDo.ReplaceConnPool(db.Statement.ConnPool)
	return o
}

func (o organizationTag) replaceDB(db *gorm.DB) organizationTag {
	o.organizationTagDo.ReplaceDB(db)
	return o
}

type organizationTagDo struct{ gen.DO }

type IOrganizationTagDo interface {
	gen.SubQuery
	Debug() IOrganizationTagDo
	WithContext(ctx context.Context) IOrganizationTagDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IOrganizationTagDo
	WriteDB() IOrganizationTagDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IOrganizationTagDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IOrganizationTagDo
	Not(conds ...gen.Condition) IOrganizationTagDo
	Or(conds ...gen.Condition) IOrganizationTagDo
	Select(conds ...field.Expr) IOrganizationTagDo
	Where(conds ...gen.Condition) IOrganizationTagDo
	Order(conds ...field.Expr) IOrganizationTagDo
	Distinct(cols ...field.Expr) IOrganizationTagDo
	Omit(cols ...field.Expr) IOrganizationTagDo
	Join(table schema.Tabler, on ...field.Expr) IOrganizationTagDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IOrganizationTagDo
	RightJoin(table schema.Tabler, on ...field.Expr) IOrganizationTagDo
	Group(cols ...field.Expr) IOrganizationTagDo
	Having(conds ...gen.Condition) IOrganizationTagDo
	Limit(limit int) IOrganizationTagDo
	Offset(offset int) IOrganizationTagDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IOrganizationTagDo
	Unscoped() IOrganizationTagDo
	Create(values ...*model.OrganizationTag) error
	CreateInBatches(values []*model.OrganizationTag, batchSize int) error
	Save(values ...*model.OrganizationTag) error
	First() (*model.OrganizationTag, error)
	Take() (*model.OrganizationTag, error)
	Last() (*model.OrganizationTag, error)
	Find() ([]*model.OrganizationTag, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.OrganizationTag, err error)
	FindInBatches(result *[]*model.OrganizationTag, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.OrganizationTag) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IOrganizationTagDo
	Assign(attrs ...field.AssignExpr) IOrganizationTagDo
	Joins(fields ...field.RelationField) IOrganizationTagDo
	Preload(fields ...field.RelationField) IOrganizationTagDo
	FirstOrInit() (*model.OrganizationTag, error)
	FirstOrCreate() (*model.OrganizationTag, error)
	FindByPage(offset int, limit int) (result []*model.OrganizationTag, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IOrganizationTagDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (o organizationTagDo) Debug() IOrganizationTagDo {
	return o.withDO(o.DO.Debug())
}

func (o organizationTagDo) WithContext(ctx context.Context) IOrganizationTagDo {
	return o.withDO(o.DO.WithContext(ctx))
}

func (o organizationTagDo) ReadDB() IOrganizationTagDo {
	return o.Clauses(dbresolver.Read)
}

func (o organizationTagDo) WriteDB() IOrganizationTagDo {
	return o.Clauses(dbresolver.Write)
}

func (o organizationTagDo) Session(config *gorm.Session) IOrganizationTagDo {
	return o.withDO(o.DO.Session(config))
}

func (o organizationTagDo) Clauses(conds ...clause.Expression) IOrganizationTagDo {
	return o.withDO(o.DO.Clauses(conds...))
}

func (o organizationTagDo) Returning(value interface{}, columns ...string) IOrganizationTagDo {
	return o.withDO(o.DO.Returning(value, columns...))
}

func (o organizationTagDo) Not(conds ...gen.Condition) IOrganizationTagDo {
	return o.withDO(o.DO.Not(conds...))
}

func (o organizationTagDo) Or(conds ...gen.Condition) IOrganizationTagDo {
	return o.withDO(o.DO.Or(conds...))
}

func (o organizationTagDo) Select(conds ...field.Expr) IOrganizationTagDo {
	return o.withDO(o.DO.Select(conds...))
}

func (o organizationTagDo) Where(conds ...gen.Condition) IOrganizationTagDo {
	return o.withDO(o.DO.Where(conds...))
}

func (o organizationTagDo) Order(conds ...field.Expr) IOrganizationTagDo {
	return o.withDO(o.DO.Order(conds...))
}

func (o organizationTagDo) Distinct(cols ...field.Expr) IOrganizationTagDo {
	return o.withDO(o.DO.Distinct(cols...))
}

func (o organizationTagDo) Omit(cols ...field.Expr) IOrganizationTagDo {
	return o.withDO(o.DO.Omit(cols...))
}

func (o organizationTagDo) Join(table schema.Tabler, on ...field.Expr) IOrganizationTagDo {
	return o.withDO(o.DO.Join(table, on...))
}

func (o organizationTagDo) LeftJoin(table schema.Tabler, on ...field.Expr) IOrganizationTagDo {
	return o.withDO(o.DO.LeftJoin(table, on...))
}

func (o organizationTagDo) RightJoin(table schema.Tabler, on ...field.Expr) IOrganizationTagDo {
	return o.withDO(o.DO.RightJoin(table, on...))
}

func (o organizationTagDo) Group(cols ...field.Expr) IOrganizationTagDo {
	return o.withDO(o.DO.Group(cols...))
}

func (o organizationTagDo) Having(conds ...gen.Condition) IOrganizationTagDo {
	return o.withDO(o.DO.Having(conds...))
}

func (o organizationTagDo) Limit(limit int) IOrganizationTagDo {
	return o.withDO(o.DO.Limit(limit))
}

func (o organizationTagDo) Offset(offset int) IOrganizationTagDo {
	return o.withDO(o.DO.Offset(offset))
}

func (o organizationTagDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IOrganizationTagDo {
	return o.withDO(o.DO.Scopes(funcs...))
}

func (o organizationTagDo) Unscoped() IOrganizationTagDo {
	return o.withDO(o.DO.Unscoped())
}

func (o organizationTagDo) Create(values ...*model.OrganizationTag) error {
	if len(values) == 0 {
		return nil
	}
	return o.DO.Create(values)
}

func (o organizationTagDo) CreateInBatches(values []*model.OrganizationTag, batchSize int) error {
	return o.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (o organizationTagDo) Save(values ...*model.OrganizationTag) error {
	if len(values) == 0 {
		return nil
	}
	return o.DO.Save(values)
}

func (o organizationTagDo) First() (*model.OrganizationTag, error) {
	if result, err := o.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.OrganizationTag), nil
	}
}

func (o organizationTagDo) Take() (*model.OrganizationTag, error) {
	if result, err := o.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.OrganizationTag), nil
	}
}

func (o organizationTagDo) Last() (*model.OrganizationTag, error) {
	if result, err := o.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.OrganizationTag), nil
	}
}

func (o organizationTagDo) Find() ([]*model.OrganizationTag, error) {
	result, err := o.DO.Find()
	return result.([]*model.OrganizationTag), err
}

func (o organizationTagDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.OrganizationTag, err error) {
	buf := make([]*model.OrganizationTag, 0, batchSize)
	err = o.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (o organizationTagDo) FindInBatches(result *[]*model.OrganizationTag, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return o.DO.FindInBatches(result, batchSize, fc)
}

func (o organizationTagDo) Attrs(attrs ...field.AssignExpr) IOrganizationTagDo {
	return o.withDO(o.DO.Attrs(attrs...))
}

func (o organizationTagDo) Assign(attrs ...field.AssignExpr) IOrganizationTagDo {
	return o.withDO(o.DO.Assign(attrs...))
}

func (o organizationTagDo) Joins(fields ...field.RelationField) IOrganizationTagDo {
	for _, _f := range fields {
		o = *o.withDO(o.DO.Joins(_f))
	}
	return &o
}

func (o organizationTagDo) Preload(fields ...field.RelationField) IOrganizationTagDo {
	for _, _f := range fields {
		o = *o.withDO(o.DO.Preload(_f))
	}
	return &o
}

func (o organizationTagDo) FirstOrInit() (*model.OrganizationTag, error) {
	if result, err := o.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.OrganizationTag), nil
	}
}

func (o organizationTagDo) FirstOrCreate() (*model.OrganizationTag, error) {
	if result, err := o.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.OrganizationTag), nil
	}
}

func (o organizationTagDo) FindByPage(offset int, limit int) (result []*model.OrganizationTag, count int64, err error) {
	result, err = o.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = o.Offset(-1).Limit(-1).Count()
	return
}

func (o organizationTagDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = o.Count()
	if err != nil {
		return
	}

	err = o.Offset(offset).Limit(limit).Scan(result)
	return
}

func (o organizationTagDo) Scan(result interface{}) (err error) {
	return o.DO.Scan(result)
}

func (o organizationTagDo) Delete(models ...*model.OrganizationTag) (result gen.ResultInfo, err error) {
	return o.DO.Delete(models)
}

func (o *organizationTagDo) withDO(do gen.Dao) *organizationTagDo {
	o.DO = *do.(*gen.DO)
	return o
}
