// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameChunkInfo = "chunk_info"

// ChunkInfo mapped from table <chunk_info>
type ChunkInfo struct {
	ID          int64  `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	FileMd5     string `gorm:"column:file_md5;type:varchar(32);not null;comment:MD5" json:"file_md5"` // MD5
	ChunkIndex  int32  `gorm:"column:chunk_index;type:int;not null" json:"chunk_index"`
	ChunkMd5    string `gorm:"column:chunk_md5;type:varchar(32);not null;comment:MD5" json:"chunk_md5"` // MD5
	StoragePath string `gorm:"column:storage_path;type:varchar(255);not null" json:"storage_path"`
}

// TableName ChunkInfo's table name
func (*ChunkInfo) TableName() string {
	return TableNameChunkInfo
}
