// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameDocumentVector = "document_vectors"

// DocumentVector mapped from table <document_vectors>
type DocumentVector struct {
	VectorID     int64   `gorm:"column:vector_id;type:bigint;primaryKey;autoIncrement:true" json:"vector_id"`
	FileMd5      string  `gorm:"column:file_md5;type:varchar(32);not null;comment:MD5" json:"file_md5"` // MD5
	ChunkID      int32   `gorm:"column:chunk_id;type:int;not null" json:"chunk_id"`
	TextContent  *string `gorm:"column:text_content;type:text" json:"text_content"`
	ModelVersion *string `gorm:"column:model_version;type:varchar(32)" json:"model_version"`
	UserID       string  `gorm:"column:user_id;type:varchar(64);not null;comment:ID" json:"user_id"` // ID
	OrgTag       *string `gorm:"column:org_tag;type:varchar(50)" json:"org_tag"`
	IsPublic     bool    `gorm:"column:is_public;type:tinyint(1);not null" json:"is_public"`
}

// TableName DocumentVector's table name
func (*DocumentVector) TableName() string {
	return TableNameDocumentVector
}
