// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameFileUpload = "file_upload"

// FileUpload mapped from table <file_upload>
type FileUpload struct {
	ID        int64      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	FileMd5   string     `gorm:"column:file_md5;type:varchar(32);not null;uniqueIndex:uk_md5_user,priority:1;comment: MD5" json:"file_md5"` //  MD5
	FileName  string     `gorm:"column:file_name;type:varchar(255);not null" json:"file_name"`
	TotalSize int64      `gorm:"column:total_size;type:bigint;not null" json:"total_size"`
	Status    int32      `gorm:"column:status;type:tinyint;not null" json:"status"`
	UserID    string     `gorm:"column:user_id;type:varchar(64);not null;uniqueIndex:uk_md5_user,priority:2;index:idx_user,priority:1;comment: ID" json:"user_id"` //  ID
	OrgTag    *string    `gorm:"column:org_tag;type:varchar(50);index:idx_org_tag,priority:1" json:"org_tag"`
	IsPublic  bool       `gorm:"column:is_public;type:tinyint(1);not null" json:"is_public"`
	CreatedAt time.Time  `gorm:"column:created_at;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	MergedAt  *time.Time `gorm:"column:merged_at;type:timestamp" json:"merged_at"`
}

// TableName FileUpload's table name
func (*FileUpload) TableName() string {
	return TableNameFileUpload
}
