// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameOrganizationTag = "organization_tags"

// OrganizationTag mapped from table <organization_tags>
type OrganizationTag struct {
	TagID       string     `gorm:"column:tag_id;type:varchar(255);primaryKey" json:"tag_id"`
	Name        string     `gorm:"column:name;type:varchar(100);not null" json:"name"`
	Description *string    `gorm:"column:description;type:text" json:"description"`
	ParentTag   *string    `gorm:"column:parent_tag;type:varchar(255);index:parent_tag,priority:1;comment:ID" json:"parent_tag"`    // ID
	CreatedBy   int64      `gorm:"column:created_by;type:bigint;not null;index:created_by,priority:1;comment:ID" json:"created_by"` // ID
	CreatedAt   *time.Time `gorm:"column:created_at;type:timestamp;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt   *time.Time `gorm:"column:updated_at;type:timestamp;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName OrganizationTag's table name
func (*OrganizationTag) TableName() string {
	return TableNameOrganizationTag
}
