// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID         int64      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	Username   string     `gorm:"column:username;type:varchar(255);not null;uniqueIndex:username,priority:1;index:idx_username,priority:1" json:"username"`
	Password   string     `gorm:"column:password;type:varchar(255);not null" json:"password"`
	Role       string     `gorm:"column:role;type:enum('USER','ADMIN');not null;default:USER" json:"role"`
	OrgTags    *string    `gorm:"column:org_tags;type:varchar(255)" json:"org_tags"`
	PrimaryOrg *string    `gorm:"column:primary_org;type:varchar(50)" json:"primary_org"`
	CreatedAt  *time.Time `gorm:"column:created_at;type:timestamp;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt  *time.Time `gorm:"column:updated_at;type:timestamp;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
